### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by andrewhodel** [pipe/webcam#3] opened 2020-11-29 23:34 UTC
If you understand how to take the stdout from raspivid and assemble it correctly to have it work as video using webRTC and RTCDataChannel, why do you want to use RTP?

I have the data streaming through a simple TCP socket (which is easy to make a websocket of, I've written the websocket protocol in C!) to the browser.

Why don't we try to make this more simple, and just have a C (or nodejs) program that accepts the piped data from raspivid and streams it to the browser?

**Comment by andrewhodel** [comment] 2020-11-29 23:35
By understand, I mean re-assemble the frames from raspivid into data the browser expects.  NAL, SFU, FU.

**Comment by andrewhodel** [comment] 2020-11-30 02:17
What I have currently is a small process that runs on the pi (zero w usually, of which I have 5) that streams the raw h264 stream from raspivid to a server which relays it over http.

Any computer with mplayer/ffmpeg or omxplayer can watch any camera from any nat scenario without issue, also any http client can download the stream to a file to be replayed.

Of course the pi's with the cameras can record video to disk and if there is a connection loss, upload the missing data to the server by checking a delta.

Also of course, the server can keep all the video data and motion detection can be placed anywhere in line (bandwidth availability dependant).

If you catch my drift, why not help me out with the raw h264 -> RTCDataChannel stuff if you have already done it?

**Comment by steely-glint** [comment] 2020-11-30 10:00
Hi, my initial version of this code was indeed data channel only. It sent 5 jpeg frames a second over the datachannel.
It worked ok, but it wasn't usable for remote steering a droid in realtime, since in low bandwidth conditions the latency built up.

You'll get significantly worse real-time performance and higher latency over http(s) than over webRTC. WebRTC was designed to do this well, it supports congestion control, dynamic bandwidth management, NAK for lost packets, PLI for starting streams in the middle etc. (i.e a lot of work has gone into it)

I'm not especially interested in forwarding http streams via servers, this adds latency and decreases security. The |pipe| solution gives low latency and e2e encryption. 

Unfortunately you can't just (yet) feed raw h264 frames to an html5 <video> element - it expects either a 'streaming' source like HLS/DASH or a webRTC MediaStream, so you'd need to fake HLS or DASH somehow. (The WebRTC NV working group is discussing this sort of API, but it will be quite a while before it gets into production browsers.)

So for now WebRTC is the best we can do - hence the |pipe| webRTC stack.

**Comment by steely-glint** [comment] 2020-11-30 10:05
Oh, and I don't do any h264 packetization/depacketization (or understand NALs etc) in this model gstreamer does all of that - |pipe| just adds the webRTC wrapper around the RTP packets so that a browser will accept them.

I gave a talk about this https://www.youtube.com/watch?v=e-Xdk8muQUg

**Comment by steely-glint** [comment] 2020-11-30 10:07
If there are specific things you need this webRTC implementation to do, please file a new issue outlining what it doesn't do currently and I'll look at adding that. (I'll close this more general discussion here.)

**Closed as completed by steely-glint** 2020-11-30 10:07 UTC
